2020-07-28 13:43:28,761 (32214/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-07-28 13:43:28,761 (32214/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-07-28 13:43:28,767 (32214/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2020-07-28 13:43:41,395 (33136/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-07-28 13:43:41,396 (33136/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-07-28 13:43:41,402 (33136/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2020-07-28 14:19:28,240 (71353/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-07-28 14:19:28,241 (71353/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-07-28 14:19:28,376 (71353/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  role "phauser" does not exist\n\n'
2020-07-28 14:19:49,844 (72792/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-07-28 14:19:49,844 (72792/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-07-28 14:19:49,921 (72792/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  role "ppuser" does not exist\n\n'
2020-07-28 14:20:09,132 (74150/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-07-28 14:20:09,133 (74150/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-07-28 14:20:09,205 (74150/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  role "ppuser" does not exist\n\n'
2020-07-28 14:32:45,342 (27014/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-07-28 14:32:45,343 (27014/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-07-28 14:32:45,458 (27014/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  role "ppuser" does not exist\n\n'
2020-07-28 14:33:15,009 (29287/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-07-28 14:33:15,009 (29287/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-07-28 14:33:15,078 (29287/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  role "ppuser" does not exist\n\n'
2020-07-28 14:33:27,390 (30327/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-07-28 14:33:27,391 (30327/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-07-28 14:33:27,403 (30327/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  role "ppuser" does not exist\n\n'
2020-07-28 14:33:52,389 (32028/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-07-28 14:33:52,390 (32028/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-07-28 14:33:52,458 (32028/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  role "ppuser" does not exist\n\n'
2020-07-28 14:41:40,959 (63749/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-07-28 14:41:40,960 (63749/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-07-28 14:41:41,069 (63749/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  role "ppuser" does not exist\n\n'
2020-07-28 14:55:02,814 (18029/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2020-07-28 14:55:02,815 (18029/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2020-07-28 14:55:02,899 (18029/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 562, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/main.py", line 549, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/Cellar/pgcli/3.0.0/libexec/lib/python3.8/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  role "root" does not exist\n\n'
2021-01-13 16:50:06,420 (12226/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-13 16:50:06,420 (12226/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-13 16:50:06,424 (12226/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2021-01-13 16:50:28,306 (13116/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-13 16:50:28,306 (13116/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-13 16:50:28,309 (13116/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2021-01-13 16:50:38,292 (13688/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-13 16:50:38,292 (13688/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-13 16:50:38,296 (13688/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/Cellar/pgcli/3.1.0/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2021-01-13 16:52:06,304 (18066/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-13 16:52:06,305 (18066/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-13 16:52:06,309 (18066/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2021-01-13 16:52:32,539 (19262/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-13 16:52:32,539 (19262/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-01-13 16:52:43,597 (19262/MainThread) pgcli.pgexecute ERROR - sql: 'show table', error: SyntaxError('syntax error at or near "table"\nLINE 1: show table\n             ^\n')
2021-01-13 16:52:43,598 (19262/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "table"\nLINE 1: show table\n             ^\n\n'
2021-01-13 16:52:44,861 (19262/MainThread) pgcli.pgexecute ERROR - sql: 'show tables', error: UndefinedObject('unrecognized configuration parameter "tables"\n')
2021-01-13 16:52:44,861 (19262/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "tables"\n\n'
2021-01-13 16:54:31,912 (19262/MainThread) pgcli.pgexecute ERROR - sql: 'select public', error: UndefinedColumn('column "public" does not exist\nLINE 1: select public\n               ^\n')
2021-01-13 16:54:31,912 (19262/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "public" does not exist\nLINE 1: select public\n               ^\n\n'
2021-01-13 16:55:20,242 (19262/MainThread) pgcli.pgexecute ERROR - sql: 'drop table public.DELETED_User_Policy', error: UndefinedTable('table "deleted_user_policy" does not exist\n')
2021-01-13 16:55:20,242 (19262/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: table "deleted_user_policy" does not exist\n\n'
2021-01-13 20:12:21,642 (71234/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-01-13 20:12:21,643 (71234/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-02-09 14:01:20,484 (35854/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-02-09 14:01:20,485 (35854/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-02-09 14:01:20,492 (35854/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2021-02-09 14:12:52,104 (63799/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-02-09 14:12:52,105 (63799/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-02-09 14:12:58,714 (63799/MainThread) pgcli.pgexecute ERROR - sql: 'show', error: SyntaxError('syntax error at end of input\nLINE 1: show\n            ^\n')
2021-02-09 14:12:58,714 (63799/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 1: show\n            ^\n\n'
2021-02-09 14:13:04,006 (63799/MainThread) pgcli.pgexecute ERROR - sql: 'show tables', error: UndefinedObject('unrecognized configuration parameter "tables"\n')
2021-02-09 14:13:04,007 (63799/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "tables"\n\n'
2021-02-09 14:15:08,663 (63799/MainThread) pgcli.pgexecute ERROR - sql: 'help', error: SyntaxError('syntax error at or near "help"\nLINE 1: help\n        ^\n')
2021-02-09 14:15:08,663 (63799/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "help"\nLINE 1: help\n        ^\n\n'
2021-02-09 15:05:46,475 (63799/MainThread) pgcli.pgexecute ERROR - sql: 'ecit', error: OperationalError('SSL connection has been closed unexpectedly\n')
2021-02-09 15:05:46,476 (63799/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: SSL connection has been closed unexpectedly\n\n'
2021-02-09 15:05:46,476 (63799/MainThread) pgcli.main ERROR - sql: 'ecit', error: OperationalError('SSL connection has been closed unexpectedly\n')
2021-02-09 15:05:46,478 (63799/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 654, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 901, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: SSL connection has been closed unexpectedly\n\n'
2021-02-09 15:06:58,273 (98661/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-02-09 15:06:58,273 (98661/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-15 12:15:50,644 (51487/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-15 12:15:50,645 (51487/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-15 12:15:50,652 (51487/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2021-04-15 12:16:37,340 (53885/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-15 12:16:37,341 (53885/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-15 12:16:37,344 (53885/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2021-04-15 12:16:52,582 (54497/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-15 12:16:52,582 (54497/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-15 12:16:52,585 (54497/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5601"?\n\n'
2021-04-15 12:17:17,894 (55639/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-15 12:17:17,895 (55639/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-15 12:17:20,031 (55639/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/usr/local/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/usr/local/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/usr/local/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2021-04-15 12:17:52,503 (57034/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-15 12:17:52,503 (57034/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-15 17:25:40,176 (57034/MainThread) pgcli.pgexecute ERROR - sql: "select kcu.table_schema,\n        kcu.table_name,\n        tco.constraint_name,\n        kcu.ordinal_position as position,\n        kcu.column_name as key_column\n from information_schema.table_constraints tco\n join information_schema.key_column_usage kcu\n      on kcu.constraint_name = tco.constraint_name\n      and kcu.constraint_schema = tco.constraint_schema\n      and kcu.constraint_name = tco.constraint_name\n where tco.constraint_type = 'PRIMARY KEY'\n and nsp.namespace = 'public'\n order by kcu.table_schema,\n          kcu.table_name,\n          position", error: UndefinedTable('missing FROM-clause entry for table "nsp"\nLINE 12:  and nsp.namespace = \'public\'\n              ^\n')
2021-04-15 17:25:40,177 (57034/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: missing FROM-clause entry for table "nsp"\nLINE 12:  and nsp.namespace = \'public\'\n              ^\n\n'
2021-04-15 17:26:10,319 (57034/MainThread) pgcli.pgexecute ERROR - sql: "select kcu.table_schema,\n        kcu.table_name,\n        tco.constraint_name,\n        kcu.ordinal_position as position,\n        kcu.column_name as key_column\n from information_schema.table_constraints tco\n join information_schema.key_column_usage kcu\n      on kcu.constraint_name = tco.constraint_name\n      and kcu.constraint_schema = tco.constraint_schema\n      and kcu.constraint_name = tco.constraint_name\n where tco.constraint_type = 'PRIMARY KEY'\n and nsp.nspname = 'public'\n order by kcu.table_schema,\n          kcu.table_name,\n          position", error: UndefinedTable('missing FROM-clause entry for table "nsp"\nLINE 12:  and nsp.nspname = \'public\'\n              ^\n')
2021-04-15 17:26:10,319 (57034/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: missing FROM-clause entry for table "nsp"\nLINE 12:  and nsp.nspname = \'public\'\n              ^\n\n'
2021-04-16 09:05:56,250 (33102/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-04-16 09:05:56,251 (33102/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-04-16 09:06:11,325 (33102/MainThread) pgcli.pgexecute ERROR - sql: "CREATE OR REPLACE FUNCTION return_table_keys()\nRETURNS TABLE (\n  table_name VARCHAR,\n  constraint_name VARCHAR,\n  position INT,\n  key_column VARCHAR\n) AS $$\nBEGIN\n    RETURN QUERY select kcu.table_name,\n            tco.constraint_name,\n            kcu.ordinal_position as position,\n            kcu.column_name as key_column\n     from information_schema.table_constraints tco\n     join information_schema.key_column_usage kcu\n          on kcu.constraint_name = tco.constraint_name\n          and kcu.constraint_schema = tco.constraint_schema\n          and kcu.constraint_name = tco.constraint_name\n     where tco.constraint_type = 'PRIMARY KEY'\n     and kcu.table_schema = 'public'\n     order by kcu.table_name,\n              position;\nEND; $$", error: SyntaxError('syntax error at or near "position"\nLINE 5:   position INT,\n          ^\n')
2021-04-16 09:06:11,327 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "position"\nLINE 5:   position INT,\n          ^\n\n'
2021-04-16 09:06:41,739 (33102/MainThread) pgcli.pgexecute ERROR - sql: "CREATE OR REPLACE FUNCTION return_table_keys()\nRETURNS TABLE (\n  table_name VARCHAR,\n  constraint_name VARCHAR,\n  key_position INT,\n  key_column VARCHAR\n) AS $$\nBEGIN\n    RETURN QUERY select kcu.table_name,\n            tco.constraint_name,\n            kcu.ordinal_position as position,\n            kcu.column_name as key_column\n     from information_schema.table_constraints tco\n     join information_schema.key_column_usage kcu\n          on kcu.constraint_name = tco.constraint_name\n          and kcu.constraint_schema = tco.constraint_schema\n          and kcu.constraint_name = tco.constraint_name\n     where tco.constraint_type = 'PRIMARY KEY'\n     and kcu.table_schema = 'public'\n     order by kcu.table_name,\n              position;\nEND; $$", error: InvalidFunctionDefinition('no language specified\n')
2021-04-16 09:06:41,740 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidFunctionDefinition: no language specified\n\n'
2021-04-16 09:08:09,951 (33102/MainThread) pgcli.pgexecute ERROR - sql: 'return_table_keys()', error: SyntaxError('syntax error at or near "return_table_keys"\nLINE 1: return_table_keys()\n        ^\n')
2021-04-16 09:08:09,951 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "return_table_keys"\nLINE 1: return_table_keys()\n        ^\n\n'
2021-04-16 09:08:25,984 (33102/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from return_table_keys()', error: UndefinedFunction('function return_table_keys() does not exist\nLINE 1: SELECT * from return_table_keys()\n                      ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n')
2021-04-16 09:08:25,984 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedFunction: function return_table_keys() does not exist\nLINE 1: SELECT * from return_table_keys()\n                      ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n\n'
2021-04-16 09:08:47,777 (33102/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from return_table_keys()', error: UndefinedColumn('column "position" does not exist\nLINE 13:               position\n                       ^\nQUERY:  select kcu.table_name,\n            tco.constraint_name,\n            kcu.ordinal_position as key_position,\n            kcu.column_name as key_column\n     from information_schema.table_constraints tco\n     join information_schema.key_column_usage kcu\n          on kcu.constraint_name = tco.constraint_name\n          and kcu.constraint_schema = tco.constraint_schema\n          and kcu.constraint_name = tco.constraint_name\n     where tco.constraint_type = \'PRIMARY KEY\'\n     and kcu.table_schema = \'public\'\n     order by kcu.table_name,\n              position\nCONTEXT:  PL/pgSQL function return_table_keys() line 3 at RETURN QUERY\n')
2021-04-16 09:08:47,777 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "position" does not exist\nLINE 13:               position\n                       ^\nQUERY:  select kcu.table_name,\n            tco.constraint_name,\n            kcu.ordinal_position as key_position,\n            kcu.column_name as key_column\n     from information_schema.table_constraints tco\n     join information_schema.key_column_usage kcu\n          on kcu.constraint_name = tco.constraint_name\n          and kcu.constraint_schema = tco.constraint_schema\n          and kcu.constraint_name = tco.constraint_name\n     where tco.constraint_type = \'PRIMARY KEY\'\n     and kcu.table_schema = \'public\'\n     order by kcu.table_name,\n              position\nCONTEXT:  PL/pgSQL function return_table_keys() line 3 at RETURN QUERY\n\n'
2021-04-16 09:09:08,370 (33102/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from return_table_keys()', error: DatatypeMismatch('structure of query does not match function result type\nDETAIL:  Returned type information_schema.sql_identifier does not match expected type character varying in column 1.\nCONTEXT:  PL/pgSQL function return_table_keys() line 3 at RETURN QUERY\n')
2021-04-16 09:09:08,370 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.DatatypeMismatch: structure of query does not match function result type\nDETAIL:  Returned type information_schema.sql_identifier does not match expected type character varying in column 1.\nCONTEXT:  PL/pgSQL function return_table_keys() line 3 at RETURN QUERY\n\n'
2021-04-16 09:09:55,204 (33102/MainThread) pgcli.pgexecute ERROR - sql: 'select kcu.table_name,\n            tco.constraint_name,\n            kcu.ordinal_position as key_position,\n            kcu.column_name as key_column\n     from information_schema.table_constraints tco', error: UndefinedTable('missing FROM-clause entry for table "kcu"\nLINE 1: select kcu.table_name,\n               ^\n')
2021-04-16 09:09:55,205 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: missing FROM-clause entry for table "kcu"\nLINE 1: select kcu.table_name,\n               ^\n\n'
2021-04-16 09:12:30,753 (33102/MainThread) pgcli.pgexecute ERROR - sql: "CREATE OR REPLACE FUNCTION return_table_keys()\nRETURNS TABLE (\n  table_name VARCHAR,\n  constraint_name VARCHAR,\n  key_position VARCHAR,\n  key_column VARCHAR\n) AS $$\nBEGIN\n    RETURN QUERY select kcu.table_name,\n            tco.constraint_name,\n            kcu.ordinal_position as key_position,\n            kcu.column_name as key_column\n     from information_schema.table_constraints tco\n     join information_schema.key_column_usage kcu\n          on kcu.constraint_name = tco.constraint_name\n          and kcu.constraint_schema = tco.constraint_schema\n          and kcu.constraint_name = tco.constraint_name\n     where tco.constraint_type = 'PRIMARY KEY'\n     and kcu.table_schema = 'public'\n     order by kcu.table_name,\n              key_position;\nEND; $$\n\nLANGUAGE 'plpgsql'", error: InvalidFunctionDefinition('cannot change return type of existing function\nDETAIL:  Row type defined by OUT parameters is different.\nHINT:  Use DROP FUNCTION return_table_keys() first.\n')
2021-04-16 09:12:30,753 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidFunctionDefinition: cannot change return type of existing function\nDETAIL:  Row type defined by OUT parameters is different.\nHINT:  Use DROP FUNCTION return_table_keys() first.\n\n'
2021-04-16 09:12:57,109 (33102/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from return_table_keys()', error: DatatypeMismatch('structure of query does not match function result type\nDETAIL:  Returned type information_schema.sql_identifier does not match expected type character varying in column 1.\nCONTEXT:  PL/pgSQL function return_table_keys() line 3 at RETURN QUERY\n')
2021-04-16 09:12:57,109 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.DatatypeMismatch: structure of query does not match function result type\nDETAIL:  Returned type information_schema.sql_identifier does not match expected type character varying in column 1.\nCONTEXT:  PL/pgSQL function return_table_keys() line 3 at RETURN QUERY\n\n'
2021-04-16 09:14:40,204 (33102/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from return_table_keys()', error: UndefinedColumn('column "position" does not exist\nLINE 13:               position\n                       ^\nQUERY:  select kcu.table_name,\n            tco.constraint_name,\n            kcu.ordinal_position as key_position,\n            kcu.column_name as key_column\n     from information_schema.table_constraints tco\n     join information_schema.key_column_usage kcu\n          on kcu.constraint_name = tco.constraint_name\n          and kcu.constraint_schema = tco.constraint_schema\n          and kcu.constraint_name = tco.constraint_name\n     where tco.constraint_type = \'PRIMARY KEY\'\n     and kcu.table_schema = \'public\'\n     order by kcu.table_name,\n              position\nCONTEXT:  PL/pgSQL function return_table_keys() line 3 at RETURN QUERY\n')
2021-04-16 09:14:40,205 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "position" does not exist\nLINE 13:               position\n                       ^\nQUERY:  select kcu.table_name,\n            tco.constraint_name,\n            kcu.ordinal_position as key_position,\n            kcu.column_name as key_column\n     from information_schema.table_constraints tco\n     join information_schema.key_column_usage kcu\n          on kcu.constraint_name = tco.constraint_name\n          and kcu.constraint_schema = tco.constraint_schema\n          and kcu.constraint_name = tco.constraint_name\n     where tco.constraint_type = \'PRIMARY KEY\'\n     and kcu.table_schema = \'public\'\n     order by kcu.table_name,\n              position\nCONTEXT:  PL/pgSQL function return_table_keys() line 3 at RETURN QUERY\n\n'
2021-04-16 09:15:06,427 (33102/MainThread) pgcli.pgexecute ERROR - sql: "sp_pkeys 'public.User_Role'", error: SyntaxError('syntax error at or near "sp_pkeys"\nLINE 1: sp_pkeys \'public.User_Role\'\n        ^\n')
2021-04-16 09:15:06,427 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "sp_pkeys"\nLINE 1: sp_pkeys \'public.User_Role\'\n        ^\n\n'
2021-04-16 09:15:59,304 (33102/MainThread) pgcli.pgexecute ERROR - sql: 'SHOW KEYS FROM public."User_Role" WHERE Key_name = \'PRIMARY\'', error: SyntaxError('syntax error at or near "FROM"\nLINE 1: SHOW KEYS FROM public."User_Role" WHERE Key_name = \'PRIMARY\'\n                  ^\n')
2021-04-16 09:15:59,304 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "FROM"\nLINE 1: SHOW KEYS FROM public."User_Role" WHERE Key_name = \'PRIMARY\'\n                  ^\n\n'
2021-04-16 09:17:52,546 (33102/MainThread) pgcli.pgexecute ERROR - sql: "SELECT a.attname, format_type(a.atttypid, a.atttypmod) AS data_type\nFROM   pg_index i\nJOIN   pg_attribute a ON a.attrelid = i.indrelid\n                     AND a.attnum = ANY(i.indkey)\nWHERE  i.indrelid = 'tablename'::regclass\nAND    i.indisprimary", error: UndefinedTable('relation "tablename" does not exist\nLINE 5: WHERE  i.indrelid = \'tablename\'::regclass\n                            ^\n')
2021-04-16 09:17:52,546 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: relation "tablename" does not exist\nLINE 5: WHERE  i.indrelid = \'tablename\'::regclass\n                            ^\n\n'
2021-04-16 09:18:04,056 (33102/MainThread) pgcli.pgexecute ERROR - sql: "SELECT a.attname, format_type(a.atttypid, a.atttypmod) AS data_type\nFROM   pg_index i\nJOIN   pg_attribute a ON a.attrelid = i.indrelid\n                     AND a.attnum = ANY(i.indkey)\nWHERE  i.indrelid = 'User_Role'::regclass\nAND    i.indisprimary", error: UndefinedTable('relation "user_role" does not exist\nLINE 5: WHERE  i.indrelid = \'User_Role\'::regclass\n                            ^\n')
2021-04-16 09:18:04,056 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: relation "user_role" does not exist\nLINE 5: WHERE  i.indrelid = \'User_Role\'::regclass\n                            ^\n\n'
2021-04-16 09:18:10,468 (33102/MainThread) pgcli.pgexecute ERROR - sql: "SELECT a.attname, format_type(a.atttypid, a.atttypmod) AS data_type\nFROM   pg_index i\nJOIN   pg_attribute a ON a.attrelid = i.indrelid\n                     AND a.attnum = ANY(i.indkey)\nWHERE  i.indrelid = 'public.User_Role'::regclass\nAND    i.indisprimary", error: UndefinedTable('relation "public.user_role" does not exist\nLINE 5: WHERE  i.indrelid = \'public.User_Role\'::regclass\n                            ^\n')
2021-04-16 09:18:10,468 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedTable: relation "public.user_role" does not exist\nLINE 5: WHERE  i.indrelid = \'public.User_Role\'::regclass\n                            ^\n\n'
2021-04-16 09:19:38,899 (33102/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from return_table_keys()', error: DatatypeMismatch('structure of query does not match function result type\nDETAIL:  Returned type information_schema.sql_identifier does not match expected type character varying in column 1.\nCONTEXT:  PL/pgSQL function return_table_keys() line 3 at RETURN QUERY\n')
2021-04-16 09:19:38,899 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.DatatypeMismatch: structure of query does not match function result type\nDETAIL:  Returned type information_schema.sql_identifier does not match expected type character varying in column 1.\nCONTEXT:  PL/pgSQL function return_table_keys() line 3 at RETURN QUERY\n\n'
2021-04-16 09:21:50,850 (33102/MainThread) pgcli.pgexecute ERROR - sql: "CREATE OR REPLACE FUNCTION return_table_keys()\nRETURNS TABLE (\n  table_name anyelement,\n  constraint_name anyelement,\n  key_column anyelement\n) AS $$\nBEGIN\n    RETURN QUERY select kcu.table_name,\n            tco.constraint_name,\n            kcu.column_name as key_column\n     from information_schema.table_constraints tco\n     join information_schema.key_column_usage kcu\n          on kcu.constraint_name = tco.constraint_name\n          and kcu.constraint_schema = tco.constraint_schema\n          and kcu.constraint_name = tco.constraint_name\n     where tco.constraint_type = 'PRIMARY KEY'\n     and kcu.table_schema = 'public'\n     order by kcu.table_name;\nEND; $$\n\nLANGUAGE 'plpgsql'", error: InvalidFunctionDefinition('cannot determine result data type\nDETAIL:  A function returning a polymorphic type must have at least one polymorphic argument.\n')
2021-04-16 09:21:50,850 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidFunctionDefinition: cannot determine result data type\nDETAIL:  A function returning a polymorphic type must have at least one polymorphic argument.\n\n'
2021-04-16 09:21:57,907 (33102/MainThread) pgcli.pgexecute ERROR - sql: "CREATE OR REPLACE FUNCTION return_table_keys()\nRETURNS TABLE (\n  table_name anyelement,\n  constraint_name anyelement,\n  key_column anyelement\n) AS $$\nBEGIN\n    RETURN QUERY select kcu.table_name,\n            tco.constraint_name,\n            kcu.column_name as key_column\n     from information_schema.table_constraints tco\n     join information_schema.key_column_usage kcu\n          on kcu.constraint_name = tco.constraint_name\n          and kcu.constraint_schema = tco.constraint_schema\n          and kcu.constraint_name = tco.constraint_name\n     where tco.constraint_type = 'PRIMARY KEY'\n     and kcu.table_schema = 'public'\n     order by kcu.table_name;\nEND; $$\n\nLANGUAGE 'plpgsql'", error: InvalidFunctionDefinition('cannot determine result data type\nDETAIL:  A function returning a polymorphic type must have at least one polymorphic argument.\n')
2021-04-16 09:21:57,907 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidFunctionDefinition: cannot determine result data type\nDETAIL:  A function returning a polymorphic type must have at least one polymorphic argument.\n\n'
2021-04-16 09:22:49,522 (33102/MainThread) pgcli.pgexecute ERROR - sql: 'DROP FUNCTION return_table_keys()', error: UndefinedFunction('function return_table_keys() does not exist\n')
2021-04-16 09:22:49,522 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedFunction: function return_table_keys() does not exist\n\n'
2021-04-16 09:23:08,700 (33102/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from return_table_keys()', error: UndefinedFunction('function return_table_keys() does not exist\nLINE 1: SELECT * from return_table_keys()\n                      ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n')
2021-04-16 09:23:08,701 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedFunction: function return_table_keys() does not exist\nLINE 1: SELECT * from return_table_keys()\n                      ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n\n'
2021-04-16 09:23:22,766 (33102/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from return_table_keysNULL::myresulttype()', error: SyntaxError('syntax error at or near "::"\nLINE 1: SELECT * from return_table_keysNULL::myresulttype()\n                                           ^\n')
2021-04-16 09:23:22,767 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "::"\nLINE 1: SELECT * from return_table_keysNULL::myresulttype()\n                                           ^\n\n'
2021-04-16 09:23:29,327 (33102/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from return_table_keys(NULL::myresulttype)', error: UndefinedObject('type "myresulttype" does not exist\nLINE 1: SELECT * from return_table_keys(NULL::myresulttype)\n                                              ^\n')
2021-04-16 09:23:29,327 (33102/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: type "myresulttype" does not exist\nLINE 1: SELECT * from return_table_keys(NULL::myresulttype)\n                                              ^\n\n'
2021-06-23 13:59:13,031 (56782/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-06-23 13:59:13,032 (56782/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-06-23 14:00:43,817 (61256/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-06-23 14:00:43,818 (61256/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-06-23 14:01:15,569 (62664/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-06-23 14:01:15,569 (62664/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-09-29 10:20:22,749 (10842/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-09-29 10:20:22,749 (10842/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-09-29 10:20:22,755 (10842/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2021-09-29 10:27:11,617 (28845/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-09-29 10:27:11,618 (28845/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-09-29 10:27:11,621 (28845/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2021-09-29 10:27:23,119 (29373/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-09-29 10:27:23,119 (29373/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-09-29 10:27:23,123 (29373/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2021-09-29 10:27:25,775 (29472/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-09-29 10:27:25,776 (29472/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-09-29 10:27:25,779 (29472/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2021-09-29 10:28:03,587 (31072/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-09-29 10:28:03,587 (31072/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-09-29 10:35:01,251 (48434/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-09-29 10:35:01,251 (48434/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-09-29 10:35:32,950 (48434/MainThread) pgcli.pgexecute ERROR - sql: 'DROP SCHEMA public CASCADE', error: InsufficientPrivilege('must be owner of schema public\n')
2021-09-29 10:35:32,951 (48434/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InsufficientPrivilege: must be owner of schema public\n\n'
2021-09-29 10:36:15,840 (48434/MainThread) pgcli.pgexecute ERROR - sql: 'GRANT ALL ON SCHEMA public TO optus_db', error: UndefinedObject('role "optus_db" does not exist\n')
2021-09-29 10:36:15,840 (48434/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: role "optus_db" does not exist\n\n'
2021-09-29 10:36:23,504 (48434/MainThread) pgcli.pgexecute ERROR - sql: 'GRANT ALL ON SCHEMA public TO optus_admihn', error: UndefinedObject('role "optus_admihn" does not exist\n')
2021-09-29 10:36:23,504 (48434/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedObject: role "optus_admihn" does not exist\n\n'
2021-09-29 10:36:29,740 (48434/MainThread) pgcli.pgexecute ERROR - sql: 'DROP SCHEMA public CASCADE', error: InsufficientPrivilege('must be owner of schema public\n')
2021-09-29 10:36:29,740 (48434/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InsufficientPrivilege: must be owner of schema public\n\n'
2021-09-29 10:38:33,116 (48434/MainThread) pgcli.pgexecute ERROR - sql: 'DROP SCHEMA public CASCADE', error: InsufficientPrivilege('must be owner of schema public\n')
2021-09-29 10:38:33,116 (48434/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InsufficientPrivilege: must be owner of schema public\n\n'
2021-09-29 10:41:22,225 (65565/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-09-29 10:41:22,225 (65565/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-09-29 10:41:39,668 (65565/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not translate host name "cxeng-optus1-bamtech-prod-beta-postgres-rds-01.cvst8iaehkxf.us-east-1.rds.amazonaws.com" to address: nodename nor servname provided, or not known\n\n'
2021-09-29 10:42:18,321 (68838/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-09-29 10:42:18,321 (68838/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-09-29 10:53:19,772 (68838/MainThread) pgcli.pgexecute ERROR - sql: 'select  \'drop table if exists "\' || tablename || \'" cascade;\' as pg_drop from pg_tables where schemaname=public', error: UndefinedColumn('column "public" does not exist\nLINE 1: ... cascade;\' as pg_drop from pg_tables where schemaname=public\n                                                                 ^\n')
2021-09-29 10:53:19,773 (68838/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "public" does not exist\nLINE 1: ... cascade;\' as pg_drop from pg_tables where schemaname=public\n                                                                 ^\n\n'
2021-09-29 10:53:29,678 (68838/MainThread) pgcli.pgexecute ERROR - sql: 'select \'drop table if exists "\' || tablename || \'" cascade;\' as pg_drop from pg_tables where schemaname=public', error: UndefinedColumn('column "public" does not exist\nLINE 1: ... cascade;\' as pg_drop from pg_tables where schemaname=public\n                                                                 ^\n')
2021-09-29 10:53:29,678 (68838/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "public" does not exist\nLINE 1: ... cascade;\' as pg_drop from pg_tables where schemaname=public\n                                                                 ^\n\n'
2021-09-29 10:53:42,472 (68838/MainThread) pgcli.pgexecute ERROR - sql: 'select \'drop table if exists "\' || tablename || \'" cascade;\' as pg_drop from pg_tables where schemaname="public"', error: UndefinedColumn('column "public" does not exist\nLINE 1: ...ascade;\' as pg_drop from pg_tables where schemaname="public"\n                                                               ^\n')
2021-09-29 10:53:42,473 (68838/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "public" does not exist\nLINE 1: ...ascade;\' as pg_drop from pg_tables where schemaname="public"\n                                                               ^\n\n'
2021-09-29 11:00:17,090 (19760/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-09-29 11:00:17,090 (19760/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-09-29 11:09:04,811 (50297/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-09-29 11:09:04,811 (50297/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-09-29 11:13:49,700 (67257/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-09-29 11:13:49,700 (67257/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-09-30 10:43:25,382 (9224/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-09-30 10:43:25,382 (9224/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-11-23 06:59:09,656 (19278/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-11-23 06:59:09,657 (19278/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2021-11-23 06:59:16,374 (19278/MainThread) pgcli.pgexecute ERROR - sql: '/dt', error: SyntaxError('syntax error at or near "/"\nLINE 1: /dt\n        ^\n')
2021-11-23 06:59:16,376 (19278/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "/"\nLINE 1: /dt\n        ^\n\n'
2022-01-17 10:31:07,905 (55625/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-17 10:31:07,906 (55625/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-22 08:26:55,939 (86220/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-22 08:26:55,940 (86220/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-22 08:27:03,872 (86220/MainThread) pgcli.pgexecute ERROR - sql: '/dt', error: SyntaxError('syntax error at or near "/"\nLINE 1: /dt\n        ^\n')
2022-02-22 08:27:03,875 (86220/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "/"\nLINE 1: /dt\n        ^\n\n'
2022-02-22 08:42:32,499 (30380/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-22 08:42:32,499 (30380/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-22 09:22:40,098 (49026/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-22 09:22:40,098 (49026/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-22 09:26:16,913 (57651/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-22 09:26:16,913 (57651/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-22 09:28:42,468 (64137/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-22 09:28:42,468 (64137/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-22 09:43:09,013 (4470/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-22 09:43:09,013 (4470/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-22 09:59:21,691 (50074/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-22 09:59:21,692 (50074/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-23 10:32:49,350 (4688/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-23 10:32:49,351 (4688/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-23 10:32:49,356 (4688/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2022-02-23 10:33:49,458 (7831/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-23 10:33:49,458 (7831/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-23 10:33:49,462 (7831/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5600"?\n\n'
2022-02-23 10:34:17,709 (9163/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-23 10:34:17,709 (9163/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-23 10:34:17,713 (9163/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5600"?\n\n'
2022-02-23 10:34:37,042 (9895/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-23 10:34:37,043 (9895/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-23 10:39:17,237 (21529/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-23 10:39:17,237 (21529/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-23 10:48:00,526 (44425/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-23 10:48:00,526 (44425/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-23 10:54:25,512 (62240/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-23 10:54:25,512 (62240/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-23 10:55:05,827 (64234/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-23 10:55:05,827 (64234/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-23 10:56:34,415 (62240/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT id, "firstName", "lastName" from public."User" where "firstName" = "Ariel"', error: UndefinedColumn('column "Ariel" does not exist\nLINE 1: ...", "lastName" from public."User" where "firstName" = "Ariel"\n                                                                ^\n')
2022-02-23 10:56:34,415 (62240/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "Ariel" does not exist\nLINE 1: ...", "lastName" from public."User" where "firstName" = "Ariel"\n                                                                ^\n\n'
2022-02-23 10:56:45,705 (62240/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from public."User" where "firstName" = "Ariel"', error: UndefinedColumn('column "Ariel" does not exist\nLINE 1: SELECT * from public."User" where "firstName" = "Ariel"\n                                                        ^\n')
2022-02-23 10:56:45,706 (62240/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "Ariel" does not exist\nLINE 1: SELECT * from public."User" where "firstName" = "Ariel"\n                                                        ^\n\n'
2022-02-23 10:56:49,412 (62240/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from public."User" where "firstName" = Ariel', error: UndefinedColumn('column "ariel" does not exist\nLINE 1: SELECT * from public."User" where "firstName" = Ariel\n                                                        ^\n')
2022-02-23 10:56:49,413 (62240/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "ariel" does not exist\nLINE 1: SELECT * from public."User" where "firstName" = Ariel\n                                                        ^\n\n'
2022-02-23 10:57:03,504 (62240/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from public."User" where "firstName" = "Super"', error: UndefinedColumn('column "Super" does not exist\nLINE 1: SELECT * from public."User" where "firstName" = "Super"\n                                                        ^\n')
2022-02-23 10:57:03,504 (62240/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "Super" does not exist\nLINE 1: SELECT * from public."User" where "firstName" = "Super"\n                                                        ^\n\n'
2022-02-23 10:57:15,657 (62240/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from public."User" where "firstName" = "Super Admin"', error: UndefinedColumn('column "Super Admin" does not exist\nLINE 1: SELECT * from public."User" where "firstName" = "Super Admin...\n                                                        ^\n')
2022-02-23 10:57:15,657 (62240/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "Super Admin" does not exist\nLINE 1: SELECT * from public."User" where "firstName" = "Super Admin...\n                                                        ^\n\n'
2022-02-23 10:57:21,582 (62240/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from public."User" where "firstName"="Super Admin"', error: UndefinedColumn('column "Super Admin" does not exist\nLINE 1: SELECT * from public."User" where "firstName"="Super Admin"\n                                                      ^\n')
2022-02-23 10:57:21,583 (62240/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "Super Admin" does not exist\nLINE 1: SELECT * from public."User" where "firstName"="Super Admin"\n                                                      ^\n\n'
2022-02-23 10:58:45,985 (62240/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from public."User" where firstName = \'Super Admin\'', error: UndefinedColumn('column "firstname" does not exist\nLINE 1: SELECT * from public."User" where firstName = \'Super Admin\'\n                                          ^\nHINT:  Perhaps you meant to reference the column "User.firstName".\n')
2022-02-23 10:58:45,986 (62240/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "firstname" does not exist\nLINE 1: SELECT * from public."User" where firstName = \'Super Admin\'\n                                          ^\nHINT:  Perhaps you meant to reference the column "User.firstName".\n\n'
2022-02-23 10:58:56,537 (62240/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from public."User" where "User.firstName" = \'Super Admin\'', error: UndefinedColumn('column "User.firstName" does not exist\nLINE 1: SELECT * from public."User" where "User.firstName" = \'Super ...\n                                          ^\n')
2022-02-23 10:58:56,537 (62240/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "User.firstName" does not exist\nLINE 1: SELECT * from public."User" where "User.firstName" = \'Super ...\n                                          ^\n\n'
2022-02-23 10:59:03,960 (62240/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from public."User" where User.firstName = \'Super Admin\'', error: SyntaxError('syntax error at or near "."\nLINE 1: SELECT * from public."User" where User.firstName = \'Super Ad...\n                                              ^\n')
2022-02-23 10:59:03,960 (62240/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "."\nLINE 1: SELECT * from public."User" where User.firstName = \'Super Ad...\n                                              ^\n\n'
2022-02-23 11:02:10,303 (64234/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from public."User" where \'User.id\' = 1', error: InvalidTextRepresentation('invalid input syntax for integer: "User.id"\nLINE 1: SELECT * from public."User" where \'User.id\' = 1\n                                          ^\n')
2022-02-23 11:02:10,304 (64234/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.InvalidTextRepresentation: invalid input syntax for integer: "User.id"\nLINE 1: SELECT * from public."User" where \'User.id\' = 1\n                                          ^\n\n'
2022-02-23 11:02:39,022 (64234/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT * from public."User" where firstName = \'Super Admin\'', error: UndefinedColumn('column "firstname" does not exist\nLINE 1: SELECT * from public."User" where firstName = \'Super Admin\'\n                                          ^\nHINT:  Perhaps you meant to reference the column "User.firstName".\n')
2022-02-23 11:02:39,022 (64234/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "firstname" does not exist\nLINE 1: SELECT * from public."User" where firstName = \'Super Admin\'\n                                          ^\nHINT:  Perhaps you meant to reference the column "User.firstName".\n\n'
2022-02-23 11:03:43,918 (64234/MainThread) pgcli.pgexecute ERROR - sql: 'clear', error: SyntaxError('syntax error at or near "clear"\nLINE 1: clear\n        ^\n')
2022-02-23 11:03:43,918 (64234/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "clear"\nLINE 1: clear\n        ^\n\n'
2022-02-23 14:34:44,745 (99004/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-23 14:34:44,746 (99004/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-23 14:38:04,840 (10443/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-23 14:38:04,841 (10443/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-23 16:12:37,889 (10443/MainThread) pgcli.pgexecute ERROR - sql: 'pgcli cxeng-optus1-bamtech-beta-postgres-aurora-rds-cluster.cluster-cqnecychbqqn.us-east-1.rds.amazonaws.com', error: SyntaxError('syntax error at or near "pgcli"\nLINE 1: pgcli cxeng-optus1-bamtech-beta-postgres-aurora-rds-cluster....\n        ^\n')
2022-02-23 16:12:37,894 (10443/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "pgcli"\nLINE 1: pgcli cxeng-optus1-bamtech-beta-postgres-aurora-rds-cluster....\n        ^\n\n'
2022-02-23 16:12:57,652 (57275/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-23 16:12:57,653 (57275/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-23 16:12:57,659 (57275/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/tmp/.s.PGSQL.5432"?\n\n'
2022-02-23 16:13:04,211 (57594/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-23 16:13:04,211 (57594/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-23 16:13:08,202 (57594/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/usr/local/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/usr/local/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/usr/local/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2022-02-23 16:13:30,746 (58654/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-23 16:13:30,746 (58654/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-23 16:13:39,574 (58654/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "optus_admin"\nFATAL:  password authentication failed for user "optus_admin"\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 578, in connect\n    pgexecute = PGExecute(\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "optus_admin"\nFATAL:  password authentication failed for user "optus_admin"\n\n'
2022-02-23 16:14:15,074 (60320/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-23 16:14:15,074 (60320/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-23 16:14:16,052 (60320/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 582, in connect\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  database "optus_admin" does not exist\n\n'
2022-02-23 16:14:33,432 (61086/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-23 16:14:33,432 (61086/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-23 16:14:38,315 (61086/MainThread) pgcli.pgexecute ERROR - sql: '\\dr', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\dr\n        ^\n')
2022-02-23 16:14:38,315 (61086/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\dr\n        ^\n\n'
2022-02-23 16:15:00,190 (61086/MainThread) pgcli.pgexecute ERROR - sql: 'select id, "firstName", "lastName"', error: UndefinedColumn('column "id" does not exist\nLINE 1: select id, "firstName", "lastName"\n               ^\n')
2022-02-23 16:15:00,191 (61086/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "id" does not exist\nLINE 1: select id, "firstName", "lastName"\n               ^\n\n'
2022-02-23 16:15:24,005 (63229/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-23 16:15:24,006 (63229/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-23 16:16:01,001 (61086/MainThread) pgcli.pgexecute ERROR - sql: 'select id, "firstName", "lastName" from "Dashboard" ORDER BY id', error: UndefinedColumn('column "firstName" does not exist\nLINE 1: select id, "firstName", "lastName" from "Dashboard" ORDER BY...\n                   ^\n')
2022-02-23 16:16:01,001 (61086/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "firstName" does not exist\nLINE 1: select id, "firstName", "lastName" from "Dashboard" ORDER BY...\n                   ^\n\n'
2022-02-25 10:16:29,072 (93862/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-25 10:16:29,073 (93862/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-02-25 10:16:32,342 (93862/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 569, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 214, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 254, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 39, in _wait_select\n    state = conn.poll()\npsycopg2.OperationalError: FATAL:  password authentication failed for user "optus_admin"\nFATAL:  password authentication failed for user "optus_admin"\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/click/termui.py", line 129, in prompt_func\n    return f("")\n  File "/usr/local/lib/python3.9/site-packages/click/termui.py", line 54, in hidden_prompt_func\n    return getpass.getpass(prompt)\n  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 77, in unix_getpass\n    passwd = _raw_input(prompt, stream, input=input)\n  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py", line 146, in _raw_input\n    line = input.readline()\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/main.py", line 572, in connect\n    passwd = click.prompt(\n  File "/usr/local/lib/python3.9/site-packages/click/termui.py", line 147, in prompt\n    value = prompt_func(prompt)\n  File "/usr/local/lib/python3.9/site-packages/click/termui.py", line 136, in prompt_func\n    raise Abort()\nclick.exceptions.Abort\n'
2022-02-25 10:16:51,843 (94680/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-02-25 10:16:51,843 (94680/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-03-01 09:38:10,288 (23045/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-03-01 09:38:10,289 (23045/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-03-01 09:40:02,906 (23045/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT id, name from public."UserDashboard" where id = 19978', error: UndefinedColumn('column "name" does not exist\nLINE 1: SELECT id, name from public."UserDashboard" where id = 19978\n                   ^\n')
2022-03-01 09:40:02,908 (23045/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "name" does not exist\nLINE 1: SELECT id, name from public."UserDashboard" where id = 19978\n                   ^\n\n'
2022-03-01 09:40:15,845 (23045/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT id, breakdow from public."UserDashboard" where id = 19978', error: UndefinedColumn('column "breakdow" does not exist\nLINE 1: SELECT id, breakdow from public."UserDashboard" where id = 1...\n                   ^\n')
2022-03-01 09:40:15,846 (23045/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 409, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/usr/local/lib/python3.9/site-packages/pgcli/pgexecute.py", line 444, in execute_normal_sql\n    cur.execute(split_sql)\npsycopg2.errors.UndefinedColumn: column "breakdow" does not exist\nLINE 1: SELECT id, breakdow from public."UserDashboard" where id = 1...\n                   ^\n\n'
